import 'package:flutter/material.dart';

/// Сопоставление символьных имён иконок (как в дизайне) с Material-иконками.
IconData appIcon(String name) {
  const map = <String, IconData>{
    'search': Icons.search_rounded,
    'bell': Icons.notifications_none_rounded,
    'heart': Icons.favorite_border_rounded,
    'heart_filled': Icons.favorite_rounded,
    'cart': Icons.shopping_cart_outlined,
    'home': Icons.home_rounded,
    'grid': Icons.grid_view_rounded,
    'box': Icons.inventory_2_outlined,
    'user': Icons.person_outline_rounded,
    'spark': Icons.auto_awesome_rounded,
    'back': Icons.arrow_back_ios_new_rounded,
    'phone': Icons.call_outlined,
    'map': Icons.location_on_outlined,
    'sort': Icons.tune_rounded,
    'chevron': Icons.chevron_right_rounded,
    'check': Icons.check_rounded,
    'truck': Icons.local_shipping_outlined,
    'plus': Icons.add_rounded,
    'edit': Icons.edit_outlined,
    'moon': Icons.dark_mode_outlined,
    'globe': Icons.public_rounded,
    'clock': Icons.access_time_rounded,
    'send': Icons.send_rounded,
    'eye': Icons.visibility_outlined,
    'package': Icons.inventory_outlined,
    'shield': Icons.shield_outlined,
    'filter': Icons.filter_list_rounded,
    'archive': Icons.archive_outlined,
    'camera': Icons.photo_camera_outlined,
    'logout': Icons.logout_rounded,
    'wallet': Icons.account_balance_wallet_outlined,
    'info': Icons.info_outline_rounded,
    'trend': Icons.trending_up_rounded,
    'chart': Icons.bar_chart_rounded,
    'list': Icons.reorder_rounded,
    'layers': Icons.layers_outlined,
    'settings': Icons.settings_outlined,
    'trash': Icons.delete_outline_rounded,
    'star': Icons.star_rounded,
    'whatsapp': Icons.chat_outlined,
    'close': Icons.close_rounded,
    'calendar': Icons.calendar_today_outlined,
    'percent': Icons.percent_rounded,
    'tag': Icons.local_offer_outlined,
    'image': Icons.image_outlined,
  };
  return map[name] ?? Icons.circle_outlined;
}
